# Generated by Django 5.0.7 on 2025-03-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_article_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
    ]
