# Generated by Django 5.0.7 on 2025-03-25 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_comment_is_approved_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_chief_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_users', to='core.subscriptionplan'),
        ),
    ]
