# Generated by Django 5.0.7 on 2025-03-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_article_likes_comment_likes_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='category',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contract_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='editor_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('published', 'Published'), ('hidden', 'Hidden')], default='draft', max_length=20),
        ),
    ]
