# Generated by Django 5.0.7 on 2025-03-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_faq_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
